### ISSUE TITLE
Explore visNetwork and Knowledge Graph Explorer

### ISSUE THREAD

**Issue by burnout87** [oda-hub/renku-aqs#20]
As suggested from the team in UZH

Knowledge Graph Explorer: [https://renkulab.io/projects/laura.kinkead/knowledge-graph-dashboard](https://renkulab.io/projects/laura.kinkead/knowledge-graph-dashboard)

visNetowrk: [https://datastorm-open.github.io/visNetwork/](https://datastorm-open.github.io/visNetwork/)

**Comment by burnout87** [comment]
Another one I just found: [https://pyvis.readthedocs.io/en/latest/index.html](https://pyvis.readthedocs.io/en/latest/index.html)

**Comment by volodymyrss** [comment]
Cool! Did you ask them by email?

**Comment by burnout87** [comment]
> Cool! Did you ask them by email?

Yes, I directly contacted one of the phd student of their group, that also presented last week.

she also said that we can contact them for questions, and also, a short zoom meeting if we want.

**Comment by volodymyrss** [comment]
> > Cool! Did you ask them by email?
> 
> Yes, I directly contacted one of the phd student of their group, that also presented last week.
> 
> she also said that we can contact them for questions, and also, a short zoom meeting if we want.

Could you please include me in CC in such requests? Especially since I initiated this inquiry.  And please forward the exchange.

**Comment by burnout87** [comment]
Did some test using **pyvis**, the most complete library that best suits our purposes, and this is the an example showing the potential:

![image](https://user-images.githubusercontent.com/3757833/145381595-95cf5189-7ce6-44be-b6b4-103cb95fb8f1.png)

**Comment by volodymyrss** [comment]
> **pyvis**

This is nice. Better than rdflib.

But, you did not respond my question. Could you please?

**Comment by burnout87** [comment]
> > **pyvis**
> 
> This is nice. Better than rdflib.

Actually I use **pydotplus/graphviz** for the all the graphical adjustments and customization (color, shapes etc).

I will keep testing and see if it is also possible to achieve more, like expanding/collapsing of nodes

> 
> But, you did not respond my question. Could you please?

**Comment by volodymyrss** [comment]
> > > **pyvis**
> > 
> > 
> > This is nice. Better than rdflib.
> 
> Actually I use **pydotplus/graphviz** for the all the graphical adjustments and customization (color, shapes etc).
> 

But you use rdflib to generate dot file?

**Comment by burnout87** [comment]
> 
> But you use rdflib to generate dot file?

Yes, but then I use **graphviz** for the graphical editing of the graph, that gives me the opportunity to more easily modify the shape, colors fonts etc etc

**Comment by volodymyrss** [comment]
I delete mostly unrelated discussion. I hope you do not protest!

Meanwhile I noted this exists, which is close to what we need eventually:

https://visjs.github.io/vis-network/examples/network/data/datasets.html

Unfortunately the pyvis integration for this particular aspect is not too advanced.
But with some JS and pyvis modifications this could be done I guess.

**Comment by burnout87** [comment]
> I delete mostly unrelated discussion. I hope you do not protest!
> 
no problem, we already discussed

> Meanwhile I noted this exists, which is close to what we need eventually:
> 
> https://visjs.github.io/vis-network/examples/network/data/datasets.html
> 
> Unfortunately the pyvis integration for this particular aspect is not too advanced. But with some JS and pyvis modifications this could be done I guess.

**pyvis** is not very complete and not even well supported, to give you an example, the functionality to generate the graph from dot-formatted data is bugged and I didn't succeed in having it working.

But **visjs** offers a high degree of customization and is a well supported library, I have already started to use it by simply injecting JS-code from the python one. And it seems to be working, I will show you at the next meeting.

**Comment by volodymyrss** [comment]
> > I delete mostly unrelated discussion. I hope you do not protest!
> 
> no problem, we already discussed
> 
> > Meanwhile I noted this exists, which is close to what we need eventually:
> > https://visjs.github.io/vis-network/examples/network/data/datasets.html
> > Unfortunately the pyvis integration for this particular aspect is not too advanced. But with some JS and pyvis modifications this could be done I guess.
> 
> **pyvis** is not very complete and not even well supported, to give you an example, the functionality to generate the graph from dot-formatted data is bugged and I didn't succeed in having it working.

I made a quick try and this works:

```python
nx = networkx.drawing.nx_pydot.read_dot('graph.dot')
g = pyvis.network.Network(notebook=True, width=800, height=600)
g.from_nx(nx)
```

https://linked-open-data.space/ (see "more")

> But **visjs** offers a high degree of customization and is a well supported library, I have already started to use it by simply injecting JS-code from the python one. And it seems to be working, I will show you at the next meeting.

Cool! Do you already upload it somewhere?

**Comment by burnout87** [comment]
> ```python
> nx = networkx.drawing.nx_pydot.read_dot('graph.dot')
> g = pyvis.network.Network(notebook=True, width=800, height=600)
> g.from_nx(nx)
> ```
> 
Ok I will try this approach too and see if I manage, I followed the docs of **pyvis**, and that approach didn't work. 

[https://pyvis.readthedocs.io/en/latest/documentation.html?highlight=from_dot#pyvis.network.Network.from_DOT](https://pyvis.readthedocs.io/en/latest/documentation.html?highlight=from_dot#pyvis.network.Network.from_DOT)

I also read on some github issues that there are bugs related to the dot-related functionality.
> 
> > But **visjs** offers a high degree of customization and is a well supported library, I have already started to use it by simply injecting JS-code from the python one. And it seems to be working, I will show you at the next meeting.
> 
> Cool! Do you already upload it somewhere?

Not yet since I first wanted to show "live", and decide together whether or not use this library, and abandon the other one for the generation of png images.

> 
> edit: Will you show the adding node functionality too?

You mean with the buttons like in the link you posted? In my code, nodes are added one-by-one, indeed because I didn't suceed with the reading of the dot-formatted data.

**Comment by volodymyrss** [comment]
> > ```python
> > nx = networkx.drawing.nx_pydot.read_dot('graph.dot')
> > g = pyvis.network.Network(notebook=True, width=800, height=600)
> > g.from_nx(nx)
> > ```
> 
> Ok I will try this approach too and see if I manage, I followed the docs of **pyvis**, and that approach didn't work.
> 
> https://pyvis.readthedocs.io/en/latest/documentation.html?highlight=from_dot#pyvis.network.Network.from_DOT
> 
> I also read on some github issues that there are bugs related to the dot-related functionality.
> 
> > > But **visjs** offers a high degree of customization and is a well supported library, I have already started to use it by simply injecting JS-code from the python one. And it seems to be working, I will show you at the next meeting.
> > 
> > 
> > Cool! Do you already upload it somewhere?
> 
> Not yet since I first wanted to show "live", and decide together whether or not use this library, and abandon the other one for the generation of png images.

I think

I would upload it in advance, so we can add the link it in agenda, and we can come further prepared. E.g. I can look it up before and have better opinion than just deciding on the spot. It does not need to be ready, any trial code. But as you wish.

> 
> > edit: Will you show the adding node functionality too?
> 
> You mean with the buttons like in the link you posted? In my code, nodes are added one-by-one, indeed because I didn't succeed with the reading of the dot-formatted data.

**Comment by burnout87** [comment]
> 
> I think it's useful if dynamic features can be managed effectively. Otherwise what's the advantage?
> 
> I would upload it in advance, so we can add the link it in agenda, and we can come further prepared. E.g. I can look it up before and have better opinion than just deciding on the spot. It does not need to be ready, any trial code. But as you wish.

I will test the other approach to read dot-formatted data. Then upload it here.

Do you have some suggestions on places I could upload an example to see it live? Like you have [here](https://linked-open-data.space/ )

> 
> Yeah. But even more - a simple but useful reaction on clicking nodes. E.g. if clicking on node hides all it's direct neighbours. Something like that.

That I am implementing it, and want indeed to show a small preview.

**Comment by volodymyrss** [comment]
> > I think it's useful if dynamic features can be managed effectively. Otherwise what's the advantage?
> > I would upload it in advance, so we can add the link it in agenda, and we can come further prepared. E.g. I can look it up before and have better opinion than just deciding on the spot. It does not need to be ready, any trial code. But as you wish.
> 
> I will test the other approach to read dot-formatted data. Then upload it here.
> 
> Do you have some suggestions on places I could upload an example to see it live? Like you have [here](https://linked-open-data.space/)

If you have html you can upload it in plenty of places.
But, you could make your own streamtlit. It's made to work with sketchiest of code.
It deploys automatically from github.

Just go there https://streamlit.io/  and follow the instructions. It''s made to be ridiculously simple to adopt.

E.g. here here is the JS I just added:

https://github.com/volodymyrss/streamlit-spiacs/blob/master/app.py#L629



> 
> > Yeah. But even more - a simple but useful reaction on clicking nodes. E.g. if clicking on node hides all it's direct neighbours. Something like that.
> 
> That I am implementing it, and want indeed to show a small preview.

Ok I tried the simplest way, not sure if that's what you do. Just to know if it's suitable.

Like [so](https://github.com/volodymyrss/streamlit-spiacs/blob/481b866fbad8179ddf8967ac80da60d81c4bab15/app.py#L629-L644)

It works (it just removes for now)!

https://linked-open-data.space/

But, I am almost convinced it will work with not so large effort at all.
Maybe we can load at once many nodes but not show all, only some. 

Then, instead of just removing the current node, we need two things:

onclick:
  * if there are any connected hidden nodes, reveal all connected nodes
  * otherwise, hide all connected nodes

Or maybe there is an existing solution.

**Comment by burnout87** [comment]
> > > ```python
> > > nx = networkx.drawing.nx_pydot.read_dot('graph.dot')
> > > g = pyvis.network.Network(notebook=True, width=800, height=600)
> > > g.from_nx(nx)
> > > ```
> > 
> > 
> > Ok I will try this approach too and see if I manage, I followed the docs of **pyvis**, and that approach didn't work.
> > https://pyvis.readthedocs.io/en/latest/documentation.html?highlight=from_dot#pyvis.network.Network.from_DOT
> 
> I made two simple attempts: with `from_DOT` (indeed, it produces nothing) and then noticed that the other function works. It's strange but it's fine.

Tried now the other approach, and it does not work properly for me :( need to investigate

**Comment by volodymyrss** [comment]
> > > > ```python
> > > > nx = networkx.drawing.nx_pydot.read_dot('graph.dot')
> > > > g = pyvis.network.Network(notebook=True, width=800, height=600)
> > > > g.from_nx(nx)
> > > > ```
> > > 
> > > 
> > > Ok I will try this approach too and see if I manage, I followed the docs of **pyvis**, and that approach didn't work.
> > > https://pyvis.readthedocs.io/en/latest/documentation.html?highlight=from_dot#pyvis.network.Network.from_DOT
> > 
> > 
> > I made two simple attempts: with `from_DOT` (indeed, it produces nothing) and then noticed that the other function works. It's strange but it's fine.
> 
> Tried now the other approach, and it does not work properly for me :( need to investigate

My example is complete in the few lines on streamlit app. Should work! But ok.

Anyway, I'd say your JS knowledge is most relevant in improving visjs presentation! It now looks to me as it can fit all of our needs.
If you produce some functions to expand/collapse the nodes (unless they exist already), many people would appreciate.

Look I found another case of KG explorer with some features we need: https://www.jamestharpe.com/json/

**Comment by burnout87** [comment]
> 
> Just go there https://streamlit.io/ and follow the instructions. It''s made to be ridiculously simple to adopt.
> 
> E.g. here here is the JS I just added:
> 
> https://github.com/volodymyrss/streamlit-spiacs/blob/master/app.py#L629
> 
> edit: I guess you can basically take this little part of my app as an example. Come back if you have any questions!
> 

Ok, it took some time, but it is indeed extremely straightforward, thanks for the suggestion!

Can you see it?

[https://share.streamlit.io/burnout87/streamlite-graph/main/main/main.py](https://share.streamlit.io/burnout87/streamlite-graph/main/main/main.py)

> 
> Then, instead of just removing the current node, we need two things:
> 
> onclick:
> 
>     * if there are any connected hidden nodes, reveal all connected nodes
> 
>     * otherwise, hide all connected nodes

This is sort of started, if you click the **action** node, more nodes and edges should hide/show, those are the related inputs and outputs for the specific **Worflow**

> 
> Or maybe there is an existing solution.

No, not really, many people only used this approach that you also tried, not difficult, but it might "explode" with more functionalities added..but certainly more powerfull

**Comment by volodymyrss** [comment]
> > Just go there https://streamlit.io/ and follow the instructions. It''s made to be ridiculously simple to adopt.
> > E.g. here here is the JS I just added:
> > https://github.com/volodymyrss/streamlit-spiacs/blob/master/app.py#L629
> > edit: I guess you can basically take this little part of my app as an example. Come back if you have any questions!
> 
> Ok, it took some time, but it is indeed extremely straightforward, thanks for the suggestion!
> 
> Can you see it?
> 
> https://share.streamlit.io/burnout87/streamlite-graph/main/main/main.py
> 
> > Then, instead of just removing the current node, we need two things:
> > onclick:
> > ```
> > * if there are any connected hidden nodes, reveal all connected nodes
> > 
> > * otherwise, hide all connected nodes
> > ```
> 
> This is sort of started, if you click the **action** node, more nodes and edges should hide/show, those are the related inputs and outputs for the specific **Worflow**

Very very nice!

> 
> > Or maybe there is an existing solution.
> 
> No, not really, many people only used this approach that you also tried, not difficult, but it might "explode" with more functionalities added..but certainly more powerfull

Next we'd probably want to fetch parts of the graph dynamically. There are public sources for more graph.
Let's see Monday!

**Comment by burnout87** [comment]
> > > Just go there https://streamlit.io/ and follow the instructions. It''s made to be ridiculously simple to adopt.
> > > E.g. here here is the JS I just added:
> > > https://github.com/volodymyrss/streamlit-spiacs/blob/master/app.py#L629
> > > edit: I guess you can basically take this little part of my app as an example. Come back if you have any questions!
> > 
> > 
> > Ok, it took some time, but it is indeed extremely straightforward, thanks for the suggestion!
> > Can you see it?
> > https://share.streamlit.io/burnout87/streamlite-graph/main/main/main.py
> > > Then, instead of just removing the current node, we need two things:
> > > onclick:
> > > ```
> > > * if there are any connected hidden nodes, reveal all connected nodes
> > > 
> > > * otherwise, hide all connected nodes
> > > ```
> > 
> > 
> > This is sort of started, if you click the **action** node, more nodes and edges should hide/show, those are the related inputs and outputs for the specific **Worflow**
> 
> Very very nice!

Take a look now, I added the selectors to dynamically tweak the physics related options, and see live how the graph reacts and behaves. Then, once happy, the new options can  be manually applied directly in the code.

**Comment by burnout87** [comment]
> 
> Yes, I saw, nice! But this minor issue (which will become bigger when many things are hidden) remains. You see, when nodes are unhidden - nothing moves. It's because it seems as physics is computed with hidden nodes taken into account. That's fine for now (a bit funny) but will become an issue if we have larger graph and hence many hidden nodes.

Yeah, it's funny but then it becomes annoying I agree. I have to find a way to have them dynamically and "find" their best position. I will keep playing, I am sure there is a way

**Comment by volodymyrss** [comment]
> > Yes, I saw, nice! But this minor issue (which will become bigger when many things are hidden) remains. You see, when nodes are unhidden - nothing moves. It's because it seems as physics is computed with hidden nodes taken into account. That's fine for now (a bit funny) but will become an issue if we have larger graph and hence many hidden nodes.
> 
> Yeah, it's funny but then it becomes annoying I agree. I have to find a way to have them dynamically "find" their best position. I will keep playing, I am sure there is a way

I think it will find itself, it has this solver. Just remove the nodes instead of hiding.

**Comment by burnout87** [comment]
Vis js  used for the implementation
