### ISSUE TITLE
collect additional references from the notebook

### ISSUE THREAD

**Issue by volodymyrss** [oda-hub/renku-aqs#24]
as suggested in #10 by @vigsterkr 

> there's a little tool that adds some additional info of a notebook: https://github.com/agoose77/jupyterlab-knowledge-graph

**Comment by burnout87** [comment]
Done with #59 and #58 . Can we close it?

**Comment by volodymyrss** [comment]
but #59 is not merged, right?

**Comment by burnout87** [comment]
True, ok once merged can be closed
