### ISSUE TITLE
Not found path(s)

### ISSUE THREAD

**Issue by burnout87** [oda-hub/renku-aqs#3]
When running the `params` command, I get the following error:

```
 "file://~/renku-aqs-test-case/.renku/Mrk 421" does not look like a valid URI, I cannot serialize this as N3/Turtle. Perhaps you wanted to urlencode it?
```

**Comment by burnout87** [comment]
I did some test, and what causes the problem is the space between `Mrk` and `421`.

I could verify it by filtering out those  object containing a space. Those probably are some annotations erroneously created.

**Comment by volodymyrss** [comment]
Those are real annotations and must be preserved. But URIs need to be constructed from names more safely.
