### ISSUE TITLE
add oda ontology to renku aqs show-graph

### ISSUE THREAD

**Issue by volodymyrss** [oda-hub/renku-aqs#31]
this one https://odahub.io/ontology/ontology.ttl

**Comment by burnout87** [comment]
In #59  the oda ontology is now loaded onto the graph and the relative nodes are visualized as connected to the parameters binding previously extracted. We have to discuss together what and how to visualize the nodes extracted from the ontology.

**Comment by volodymyrss** [comment]
could you please make a screenshot?

**Comment by burnout87** [comment]
> could you please make a screenshot?

Clearly the naming should be improved, but the idea is there. 

![image](https://github.com/oda-hub/renku-aqs/assets/3757833/10913770-2aeb-4b14-98c6-42f4244fff0d)

**Comment by volodymyrss** [comment]
Looks somehow useful already!
What about `src_name`, it's not AstroObject?
Also, are the entities harvested while intercepting astroquery also connected to ontology? In particular source name

**Comment by burnout87** [comment]
> Looks somehow useful already! 
Absolutely, we have to make sure to describe those entities we extract from the ontology with the most appropriate naming

> What about `src_name`, it's not AstroObject? 

It is, just that in the screenshot is not "expanded" (ps I wanted to put a screenshot, but I just found what it looks like a small bug :/ )

> Also, are the entities harvested while intercepting astroquery also connected to ontology? In particular source name

Yes, the plan is to link also those

**Comment by volodymyrss** [comment]
> > Also, are the entities harvested while intercepting astroquery also connected to ontology? In particular source name
> Yes, the plan is to link also those

Could you show how this works when it does? 
This is the kind of connection which will lead to useful recommendations for annotations.

**Comment by burnout87** [comment]
> > > Also, are the entities harvested while intercepting astroquery also connected to ontology? In particular source name
> > > Yes, the plan is to link also those
> 
> Could you show how this works when it does? This is the kind of connection which will lead to useful recommendations for annotations.

Absolutely, I will put a first screenshot as soon as I fix that bug (which is probably in the query)

**Comment by burnout87** [comment]
> 
> Could you show how this works when it does? This is the kind of connection which will lead to useful recommendations for annotations.

And here it is the connection for the `src_name`, which is an `AstrophysicalObject`. `src_name` (parameter_binding from the two notebooks) is an `AstrophysicalObject`, as well as, `Mrk 421`, intercepted by the plugin during the run of the notebook:

![image](https://github.com/oda-hub/renku-aqs/assets/3757833/8a17c080-2a53-4b1e-965b-8bbb52e40822)

**Comment by burnout87** [comment]
I have a question: from one of the test projects I use for the development of the graph (`fermi`), and in the `fermi_lc.ipynb` notebook (https://renkulab.io/gitlab/astronomy/mmoda/fermi/-/blob/master/fermi_lc.ipynb), the parameter `dT` is initialized with the value of `2`. `nb2rdf` assigns to it the `int`type ie `http://www.w3.org/2001/XMLSchema#int`.

![image](https://github.com/oda-hub/renku-aqs/assets/3757833/f44404d8-006e-4d2a-a6e1-ebde3c7d4b41)

However this type is not found on the current `oda` ontology, rather this is present:

``` ttl
###  http://odahub.io/ontology#Integer
:Integer rdf:type owl:Class ;
         rdfs:subClassOf :NumericParameter ,
                         [ rdf:type owl:Restriction ;
                           owl:onProperty :value ;
                           owl:allValuesFrom xsd:integer
                         ] .
```

Is the `int` type supposed to be inside the ontology? Should instead the `owl:allValuesFrom` predicate be used ?

**Comment by burnout87** [comment]
Any ideas @dsavchenko and @volodymyrss ?

**Comment by dsavchenko** [comment]
I'm not sure how to handle it. The `int` type is the fallback for the unannotated parameter derived from the python type. 
The plugin will handle it the same way as oda:Integer
Should we somehow express the equivalence in the ontology?

PS. From the point of view of the workflow developer, I'm sure this particular parameter was meant to be float. If it's annotated properly by TimeInterval with some unit, it will be a subclass of oda:Float

**Comment by burnout87** [comment]
> 



> 
> yes, we can add in ontology that it is sameAs. @burnout87 can try to add it with a PR in https://github.com/oda-hub/ontology/?

Isn't it already expressed via the `owl:allValuesFrom` ?

**Comment by dsavchenko** [comment]
> Isn't `owl:allValuesFrom` already there to express this equivalence?

In some sense yes, but somehow indirectly. I believe it's not equivalent expressions through data restriction and with sameAs
But for us, they are really the same, because they are treated in the same way

**Comment by burnout87** [comment]
With the introduction of the `equivalentClass` within the ontology, I can now relate the integer parameter with the correspondent element of the ontology

![image](https://github.com/oda-hub/renku-aqs/assets/3757833/f2d695f9-d253-407e-8bee-75f2eea25a1a)
