### ISSUE TITLE
make sure sitecustomize is used with pipinstalle drenku

### ISSUE THREAD

**Issue by volodymyrss** [oda-hub/renku-aqs#40]

**Comment by burnout87** [comment]
this is done by setting the env var...or am I misunderstanding?

**Comment by volodymyrss** [comment]
yeah well looks like you added it after this issue was created? 

https://github.com/oda-hub/renku-aqs/blob/de5dbe416cbf198b865f39667fcd1988a18c0f2c/renkuaqs/plugin.py#L104-L105

Do you confirm it works without user setting any extra variables?

**Comment by burnout87** [comment]
yes it does, it has been tested also "live"

**Comment by volodymyrss** [comment]
right, no extra variables were set. So, which PR did it? This issue should have been attached there.

**Comment by burnout87** [comment]
#42 

in particular: https://github.com/oda-hub/renku-aqs/pull/42/commits/c5768dfd8c20317712c8e72d5782bf7d35523c41
