### ISSUE TITLE
return html without writing to file

### ISSUE THREAD

**Issue by volodymyrss** [oda-hub/renku-aqs#43]
also collapsible view of the ttl in the interface

**Comment by burnout87** [comment]
when clicking on the graph button now the html is no longer written over an html files, rather directly on a stream and visualized

**Comment by burnout87** [comment]
first implementation for the ttl, need a though a better visualization:

![image](https://user-images.githubusercontent.com/3757833/219715364-6aa3e4ae-78ff-4a02-9ed5-5f88219f9ba6.png)

**Comment by volodymyrss** [comment]
It's good to have it, though I rather thought it'd be part of the same page, but some sort of "expand on click" box.

**Comment by burnout87** [comment]
yeah absolutely, I am finding now a better solution like you said, collapsible, this was in the meantime to test the visualization of the ttl content itself

**Comment by burnout87** [comment]
much better this way....

[Screencast 2023-02-17 18:48:39.webm](https://user-images.githubusercontent.com/3757833/219735187-05cef64f-9a0e-41e5-a2b6-8dd2d6e9566a.webm)

**Comment by volodymyrss** [comment]
Indeed! I'd also make the expanded block larger and maybe stretchable?

**Comment by burnout87** [comment]
Larger, and also stretchable!

[Screencast 2023-02-20 13:01:12.webm](https://user-images.githubusercontent.com/3757833/220100743-096a66b3-682e-46da-ab58-6f325564ec67.webm)

**Comment by burnout87** [comment]
Completed with #42
