### ISSUE TITLE
refresh button in the graph server

### ISSUE THREAD

**Issue by volodymyrss** [oda-hub/renku-aqs#44]

**Comment by burnout87** [comment]
First version

[Screencast 2023-02-16 20:33:58.webm](https://user-images.githubusercontent.com/3757833/219468719-da66ec4c-ae4f-41ed-92cf-6f9efd9af2b8.webm)

**Comment by burnout87** [comment]
Introduced the check of the graph version, using the revision of the repo. If necessary requery the graph

[Screencast 2023-02-21 23:05:20.webm](https://user-images.githubusercontent.com/3757833/220469359-8c77e526-f10d-46e3-9414-72b972df92de.webm)

**Comment by volodymyrss** [comment]
cool!

**Comment by burnout87** [comment]
Shall we remove the refresh button, since now this happens automatically? Or perhaps we can have it displayed only when the graph is opened statically (via the cli)

**Comment by volodymyrss** [comment]
I would keep it, to preserve the interface, maybe replace with an icon. Indeed in some situations it's useful.

**Comment by burnout87** [comment]
better this one, which uses on of the icons provided by bootstrap (theme used for the gallery)

![image](https://user-images.githubusercontent.com/3757833/221617802-a8284e66-ccf0-4e1b-bf0a-f9b3120f77e6.png)

**Comment by burnout87** [comment]
Completed with #51
