### ISSUE TITLE
make collapsible checkboxes and legend

### ISSUE THREAD

**Issue by volodymyrss** [oda-hub/renku-aqs#45]
# Advances Domain

Mention the Domain this issue addresses, e.g.: 

* UX
* resilience
* community-expanding feature

**Comment by burnout87** [comment]
First version

[Screencast 2023-03-06 17:07:12.webm](https://user-images.githubusercontent.com/3757833/223165725-524c3aea-e67b-46bb-a2bc-1e04e4591831.webm)

**Comment by volodymyrss** [comment]
nice! mildly explosive.

**Comment by burnout87** [comment]
"fine tuned"...

[Screencast 2023-02-21 23:05:20.webm](https://user-images.githubusercontent.com/3757833/223390401-42dcd22d-7e27-4b6e-87fc-1b0966b47e6a.webm)

**Comment by burnout87** [comment]
test also on renkulab, the amount of space earned improves the whole experience:

![image](https://user-images.githubusercontent.com/3757833/223398570-f500ee16-b6f5-4b37-9bb4-9415dc28aedc.png)

![image](https://user-images.githubusercontent.com/3757833/223398811-8d7a2588-5958-412b-89a9-b9d53c4cb8e3.png)

**Comment by volodymyrss** [comment]
ok! could you move them maybe? it would give even more space

![image](https://user-images.githubusercontent.com/3909535/223402721-e28f735f-7950-4bdd-8e26-7e6ff3d7c731.png)

**Comment by burnout87** [comment]
it does indeed

![image](https://user-images.githubusercontent.com/3757833/223407184-cbade68b-d638-4b9f-86fd-be1bd6a640bd.png)

**Comment by burnout87** [comment]
much better

![image](https://user-images.githubusercontent.com/3757833/223418683-2e10f1c4-d715-41a4-8b11-00a97831527d.png)
