### ISSUE TITLE
add hide option on right click

### ISSUE THREAD

**Issue by volodymyrss** [oda-hub/renku-aqs#46]
# Advances Domain

Mention the Domain this issue addresses, e.g.: 

* UX
* resilience
* community-expanding feature

**Comment by burnout87** [comment]
first "attempt":

[Screencast 2023-03-07 18:22:43.webm](https://user-images.githubusercontent.com/3757833/223500147-05383ee3-08a7-4cd7-bcd2-2c8d5dc84f38.webm)

**Comment by burnout87** [comment]
with the icon

![image](https://user-images.githubusercontent.com/3757833/224748916-1566103d-1be5-4e9d-88f9-c616c7ece442.png)

**Comment by burnout87** [comment]
The node that is selected to be hidden gets hidden along with its child nodes that dont have further child nodes (similar behavior obtained by clicking on a node that has already been expanded eg [gif](https://github.com/oda-hub/renku-aqs/blob/master/readme_imgs/animation_expansion_retraction.gif)).

Also, a button that shows back all the nodes that have been "right-clicked" hidden has been added.

**Comment by volodymyrss** [comment]
The hide button does not really work for me for some reason, could you show an example in https://renkulab.io/projects/gabriele.barni/grb-detection/sessions/new?autostart=1

**Comment by burnout87** [comment]
Ok, some changes of theJS library were not pushed to the github pages branch. I just tried myself and I can see it working...let me know we can also have a brief live session....
