### ISSUE TITLE
"activity calls query_object" instead of "query_object query activity"

### ISSUE THREAD

**Issue by volodymyrss** [oda-hub/renku-aqs#49]
also hover tip should be compatible with the arrow label

**Comment by burnout87** [comment]
Current:

![image](https://user-images.githubusercontent.com/3757833/220655136-fb17a003-5d43-49ba-892b-48545d0ccee1.png)

**Comment by burnout87** [comment]
The `hasTarget` predicate basically no longer is generated, since I could apply this change at a query level

![Screenshot from 2023-02-27 17-36-06](https://user-images.githubusercontent.com/3757833/221624033-a117abe3-a1d1-485c-85ec-e1065a282830.png)
