### ISSUE TITLE
collect nb2workflow metadata before it is even run and also during the run

### ISSUE THREAD

**Issue by volodymyrss** [oda-hub/renku-aqs#50]
use internals of nb2rdf

**Comment by burnout87** [comment]
I suppose you refer to [this](https://github.com/oda-hub/nb2workflow/blob/1ad46545ec55c005fa8a156064b828d8fe2ead2b/nb2workflow/ontology.py#L153) ?

So, briefly, given a notebook, this produces an RDF graph object that contains a number of annotations related to the notebook itself (ie input, outputs, parameters) using its tags.

Ideally, we want to collect those annotations _before_ the actual execution of the noteobok.

Am I correct?

**Comment by volodymyrss** [comment]
> I suppose you refer to [this](https://github.com/oda-hub/nb2workflow/blob/1ad46545ec55c005fa8a156064b828d8fe2ead2b/nb2workflow/ontology.py#L153) ?
> 
> So, briefly, given a notebook, this produces an RDF graph object that contains a number of annotations related to the notebook itself (ie input, outputs, parameters) using its tags.
> 
> Ideally, we want to collect those annotations _before_ the actual execution of the noteobok.
> 
> Am I correct?

Yes. Maybe there is another renku hook to use, or just run it after generating renku graph, adding this graph to it.

**Comment by burnout87** [comment]
- include type for each ParameterBinding
- only analyze output notebook
- additional command `inspect` , to inspect the input notebook and attach those info to the file itself, still using `nb2rdf`
  - add those info in a different place to  be added to the graph exported initially
  - insert also the ontology inside this graph
