### ISSUE TITLE
make possible to auto-reload graph when the error is returned?

### ISSUE THREAD

**Issue by volodymyrss** [oda-hub/renku-aqs#54]
I get this:

"""Error while generating the output graph:

Project version is outdated and a migration is required. Run `renku migrate` command to fix the issue.""

and when I migrate, the message does not go away. Could it be made so that in this case auto-reload still works?

**Comment by volodymyrss** [comment]
is this still the case?

**Comment by burnout87** [comment]
I haven't  worked on this issue yet
