### ISSUE TITLE
make simple visualization with `renku aqs` `cli`

### ISSUE THREAD

**Issue by volodymyrss** [oda-hub/renku-aqs#6]
Use [renku team tools](https://github.com/SwissDataScienceCenter/renku-python/blob/master/renku/core/commands/format/graph.py#L97) and [rdflib tools](https://github.com/RDFLib/rdflib/blob/d717cef505b07556fffc9f0e64d6c8f5b3a5b84c/rdflib/tools/rdf2dot.py)

**Comment by burnout87** [comment]
Infer the type of output based on the extension.
