### ISSUE TITLE
Improve visualization `Class` node

### ISSUE THREAD

**Issue by burnout87** [oda-hub/renku-aqs#61]
Those from the ontology

![image](https://github.com/oda-hub/renku-aqs/assets/3757833/46960670-c0f2-4769-a6b5-8c6fd44c576d)

**Comment by burnout87** [comment]
> sometimes, use the same colors for different parameters like T1, T2 

TimeInstant             |  Angle
:-------------------------:|:-------------------------:
![image](https://github.com/oda-hub/renku-aqs/assets/3757833/e420a558-d3cf-4610-a1f5-98b89a65e21d)  |  ![image](https://github.com/oda-hub/renku-aqs/assets/3757833/63948119-6990-46b9-8cf0-3d7434e1abd3)

> make "Class" small and class label large

I discovered that the vis-js library supports html in a node's label, so I just tried and this is a first example. I'll explore this part even further as perhaps it can support css class reference. In theory we could specify those directly inside the configuration.

![image](https://github.com/oda-hub/renku-aqs/assets/3757833/514f8d80-fc81-483a-bb20-0892f2d5f264)

**Comment by burnout87** [comment]
Made some more investigation and, at the current state, the vis.js library does not offer a lot html support for the nodes and edges labels. Just the basics like colors and font size. So, this is an example for the `Class` node:

![image](https://github.com/oda-hub/renku-aqs/assets/3757833/e27c8973-781f-4b33-aa6e-cb99f6f5f6d0)


What do you think? Another approach would be to remove the `OntologyClass` title and just leave the name of the class it self...but perhaps it would not be too clear what that node represents...?

![image](https://github.com/oda-hub/renku-aqs/assets/3757833/ed12dcc4-53b5-4ea9-8bd8-96cffa99e5b9)

**Comment by volodymyrss** [comment]
I like second way better, more concise. Maybe pop-up can show more info like that it's ontlogy?

**Comment by burnout87** [comment]
> I like second way better, more concise. Maybe pop-up can show more info like that it's ontlogy?

The tooltip actually shows that

![image](https://github.com/oda-hub/renku-aqs/assets/3757833/0d7dacd7-dd51-4587-bc05-7596f8cbd071)
